server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567890

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  secret: mySuperSecretKeyForJWTGeneration12345_myExtraSecureKey_987654321
  expiration: 3600000
